")))
    (float (("0.0") ("100.0") ("200.0") ("300.0") ("400.0") ("500.0") ("3.14159") ("10.0") ("9.0") ("8.0") ("7.0") ("6.0") ("5.0") ("4.0") ("3.0") ("2.0") ("1.0")
	    ("sin(" float ")") ("cos(" float ")") ("tan(" float ")")
	    ( float " + " float ) (float " - " float) (float " * " float) 
	    ("self->angles[0]") ("self->angles[1]") ("self->angles[2]") 
	    ("self->velocity[0]") ("self->velocity[1]") ("self->velocity[2]") 	    
	    ("time")
	    ("DIV(" float "," float ")") ))
    (int (("10") ("9") ("8") ("7") ("6") ("5") ("4") ("3") ("2") ("1") ("0") (int " + " int) (int " - " int) ("DIV(" int "," int")") (int " * " int) ("!" int)
    	("time") ))))
